version: '3.7'
services:
  clientnode:
    image: shmfaraz15/spe-major-frontend:latest
    container_name: clientnode
    ports:
      - "3000:3000"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.5
  servernode:
    image: shmfaraz15/spe-major-backend:latest
    container_name: servernode
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s
    ports:
      - "8081:8081"
    depends_on:
      - "dbnode"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://dbnode:3306/tourguide?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
      SPRING_DATASOURCE_USERNAME: "faraz"
      SPRING_DATASOURCE_PASSWORD: "Mysql@2810"
      DATABASE_HOST: "dbnode"
      DATABASE_PORT: "3307"
      MYSQL_DATABASE: "tourguide"
      MYSQL_USER: "faraz"
      MYSQL_PASSWORD: "Mysql@2810"
    volumes:
      - /home/faraz/Desktop/SPE_Major_TourGuide/logs/application.log:/app/logs/application.log

    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.6

  dbnode:
    image: mysql
    container_name: dbnode
    ports:
      - "3307:3306"
    volumes:
      - /home/faraz/Desktop/Sem2/docker-compose-folder/dbnode:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "Faraz"
      MYSQL_DATABASE: "tourguide"
      MYSQL_USER: "faraz"
      MYSQL_PASSWORD: "Mysql@2810"
    networks:
      net_ubuntu:
        ipv4_address: 172.28.1.7

  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
      - elastic_data:/usr/share/elasticsearch/data/
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
#    networks:
#      net_ubuntu:
#        ipv4_address: 172.28.1.8

  Logstash:
    image: logstash:7.16.2
    container_name: logstash
    restart: always
    volumes:
      - /home/faraz/Desktop/SPE_Major_TourGuide/logs:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
      - Elasticsearch
    ports:
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
#    networks:
#      net_ubuntu:
#        ipv4_address: 172.28.1.9

  Kibana:
    image: kibana:7.16.2
    container_name: kibana
    restart: always
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    depends_on:
      - Elasticsearch
#    networks:
#      net_ubuntu:
#        ipv4_address: 172.28.1.10

networks:
  net_ubuntu:
    ipam:
      driver: default
      config:
        - subnet: 172.28.1.0/24

volumes:
  elastic_data:
    driver: local